### ISSUE TITLE
handling the servlet context

### ISSUE THREAD

**Issue by yogthos** [danlarkin/clabango#1]
Currently if the application is deployed on an application server, such as tomcat, with a context other than root then static resources will not be served correctly.

Would it be possible to add something for handling the servlet context when serving static resources. For example, Hiccup provides [wrap-base-url](https://github.com/weavejester/hiccup/blob/master/src/hiccup/middleware.clj) middleware and uses it when parsing the templates.

The workaround right now would be to do something like this in the template

``` xml
<link href="{{context}}/css/screen.css" rel="stylesheet" type="text/css"></link>
```

and then pass the context in to the template

``` clojure
(render-file "mytemplate.html" {:context (:context *request*)})
```

it gets kinda tedious to do :)

**Comment by danlarkin** [comment]
I think I understand what you're asking for, but I want to ask to make sure. Are you looking for a sort of global context? One that gets merged with whatever context you provide to `render`?

**Comment by yogthos** [comment]
That would be one way, but then you'd still have to remember to prepend it to all the relative urls. I was wondering if it might be possible to do that implicitly. So, if you have a servlet context it gets prepended to relative links.

**Comment by danlarkin** [comment]
So are you saying that you want all anchors intercepted? And you want the destination rewritten to include something from a dynamic context?

If that's what you're asking for I'm afraid I don't think that's a good fit for clabango, it's a little to magicy for my taste.

Clabango is a generic templating language, there's nothing specific to HTML in here -- it should be useful for any text format, so I'm not comfortable with adding a feature like this.

**Comment by yogthos** [comment]
Ah that's a good point, I was definitely thinking from HTML templating perspective. In that case I would close the issue. There's not much value in setting a global context, since it's trivial to write a helper to do that. 

I suppose rewriting could be done outside Clabango as well, once the page is generated.

**Comment by ddillinger** [comment]
I guess I don't know if that will be a big help?

I mean, I understand not wanting to repeat yourself, but I would be concerned about two things:
1. There's magic now. This is probably getting into opinion territory, but it smells like hidden magic. This is by far the less compelling of my points though :)
2. There is no way around needing to specify that context, as soon as you have more than one of them. If you ever had a need for specifying, say, `{{static}}` and `{{app}}` or between two apps or something, whatever that need might be -- and this is before even getting into, say, "akamaizing" your site -- there isn't a good way around just needing to put the one you need into each href to distinguish it from the other(s).

**Comment by yogthos** [comment]
Those are good points actually, especially the fact that you could end up with multiple contexts. I suppose remembering to put the {{context}} in front of the uri is not the worst thing ever. :)
