### ISSUE TITLE
Custom filters don't render properly

### ISSUE THREAD

**Issue by jszakmeister** [danlarkin/clabango#10]
Thank you for writing a template engine similar to Django's and Jinja.  I've been trying to incorporate it into a prototype application, and discovered an interesting behavior.  If I create a new template tag that is identical to `upper`, but with a different name, I end up with the result being rendered as a map.

The function is this:

``` clojure
(deftemplatefilter "my-upper" [node body arg]
  (when body
    {:body (.toUpperCase body)}))
```

If I use this, I end up with the value being rendered as a map with a `:body` entry: `{:body "JOHN"}`.  If I change it to not wrap in a map, then it renders correctly.  But that seems to go against the precedent set in clabango.  Is there something broken here?

**Comment by danlarkin** [comment]
Ah yes, what you're seeing (I assume) is the difference between master and the latest stable release. In 0.5 filters had to return strings, and on master they return maps.

I don't publish snapshots to clojars... maybe it's time for me to cut a new release.

**Comment by jszakmeister** [comment]
Ah!  In that case, let me close the ticket.
