### ISSUE TITLE
parse-filters is really, really slow

### ISSUE THREAD

**Issue by bitemyapp** [danlarkin/clabango#13]
I don't know if this was the case before, but parse-filters is really slow.

The best way I can think to optimize this is to move as much of the template parsing into the pre-context-aware section and turn the filters into memoizable call-sites for injecting the data after the fact.

This would probably require writing a chunk of the parser into something that does as little as possible at the context-aware stage.

It also seems like a lot of time is being spent in the lazy-seq operations.

Do you know anything about this @danlarkin?

**Comment by danlarkin** [comment]
It doesn't surprise me that it's slow, as not much (any) time has been spent thinking about performance. If you want to explore ideas on how to speed it up that would be totally rad, thanks!
